### ISSUE TITLE
Actualización de RoadMap

### ISSUE THREAD

**Issue by milo19980525** [udistrital/cumplidos_cliente#317]
Teniendo en cuenta los líneamientos establecidos para la contratación 2023 de la oficina apoyar técnicamente en la creación del [roadmap](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7Bc8b13929-fc88-4ea1-b494-60b97b651bf8%7D&action=default&cid=667f4e85-63ba-4622-bdf7-15f1837bcd84) para SGA.

**Especificaciones técnicas**

- Establecer las actividades y subactividades del roamap relacionadas con los hitos 2, 3, 4 y 5.
- Tener en cuenta una estimación inicial en puntos de historia.
- Agrupar las actividades y subactividades en milestones o sprints teniendo en cuenta la disponibilidad del equipo.

**Sub Tareas**

- [ ] Realizar la definición de actividades y subactividades asociadas a los hitos 2, 3, 4 y 5
- [ ] Establecer en SP la estimación de las actividades y sibactividades definidas.
- [ ] Agrupar actividades y subactividades en milestones teniendo en cuenta la capacidad del equipo asumiendo dos desarrolladores tiempo completo y uno parcial.

**Criterios de aceptación**

- [ ] Comentario en issue que proporcione un resumen de las actividades agregadas al roadmap diariamente.
- [ ] Actualización de actividades en el roadmap.

**Requerimientos**

- [ ] Especificación de requerimientos (En dado caso de no tenerlos refinados aún colocar estimación inical)

**Dependencias**

- Ninguna

**Definition of Ready - DoR**

- [ ] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint.

**Comment by a52290451** [comment]
Se realiza actualización de items de trabajo en desarrollo, en cuanto a su estado y fase final.
